### ISSUE TITLE
fixture

### ISSUE THREAD

**Issue by bsr203** [nordsimon/elasticsearch-graphql-server-example#1]
Hi,

I like to try out search functionality (I am using google cloud backend, where I construct similar to elastic queries. I may use elastic later), but I am not much familiar to the data schema you use. I am running an elasticsearch server, and currently gives error

```
Elasticsearch INFO: 2016-01-23T19:01:13Z
  Adding connection to http://localhost:9200/

Elasticsearch DEBUG: 2016-01-23T19:01:13Z
  starting request { method: 'GET', path: '/orders/_mapping/order', query: {} }


Elasticsearch TRACE: 2016-01-23T19:01:13Z
  -> GET http://localhost:9200/orders/_mapping/order

  <- 404
  {
    "error": {
      "root_cause": [
        {
          "type": "index_not_found_exception",
          "reason": "no such index",
          "resource.type": "index_or_alias",
          "resource.id": "orders",
          "index": "orders"
        }
      ],
      "type": "index_not_found_exception",
      "reason": "no such index",
      "resource.type": "index_or_alias",
      "resource.id": "orders",
      "index": "orders"
    },
    "status": 404
  }

```

could you please provide the fixture data you use to test this, and possibly the commands to issue.

thank again for open sourcing this.
bsr.

**Comment by nordsimon** [comment]
Hello

The application tries to fetch the mapping from the search index you've specified, since no search index exists it fails.

Try to insert a first document, then the index will be created and the fields title and order will get a mapping:

```
curl -X PUT -d '{"title": "My order", "description": "Order description"}' localhost:9200/orders/order/1
```

Start the server and see if it works better this time

/ Simon

**Comment by bsr203** [comment]
thanks Simon. that did it.

I am not sure proper query structure though. The example provided at https://github.com/nordsimon/elasticsearch-graphql#query-builder didn't work.

graphiql shows the schema for `Filter` is 

```
description: filter_3
title: filter_6
```

where `filter_3` is 

```
operator: FilterType_2
value: String
values: [String]
```

Is this the intended structure. 

thanks.

**Comment by nordsimon** [comment]
The structure is built from the fields you have in your order documents. So if you added the document you will get both filter and aggregation for title and description

My example query is based upon the documents I have. To try this for real, I would create an index and put a number of documents so you have something to search for and aggregate on.

/ simon

**Comment by bsr203** [comment]
thanks you. I will explore elasticsearch further.
